### PR TITLE
JBPM-5551 - Timer start event triggered every second cycle

### PR DESCRIPTION
**Pull request by mswiderski**
depends on https://github.com/droolsjbpm/jbpm/pull/739

@sutaakar do you mind having a look?

### CODE REVIEW

**Comment by mswiderski** [comment]
jenkins retest this

**Comment by sutaakar** [comment]
@mswiderski Looks good. Just one idea, shouldn't it be better to place such test to Engine in container test suite - https://github.com/droolsjbpm/jbpm/tree/master/jbpm-container-test/jbpm-in-container-test - as this is engine issue?
What do you think?

**Comment by mswiderski** [comment]
main reason I put it here is that we test it on all containers (wildfly, eap, was, wls) and not sure we do that for jbpm-in-container-test

**Comment by sutaakar** [comment]
AFAIK jbpm-in-container-tests should be executed on all containers too. @MarianMacik Is it so?

**Comment by mswiderski** [comment]
if that's the case then it's surely makes sense to have it there

**Comment by mswiderski** [comment]
@sutaakar what do you think at merging this and later on add tests to jbpm if we confirm it does what we need?

**Comment by sutaakar** [comment]
I agree.

**Pull request merged**
