### PR TITLE
DROOLS-733 - Added default sorting for Process Definitions retrieval …

### PR DESCRIPTION
**Pull request by sutaakar**
…without filtering

### CODE REVIEW

**Comment by mswiderski** [comment]
this is already done on this commit:
https://github.com/droolsjbpm/droolsjbpm-integration/commit/605847a14e6fc3634c341020d89ac5b23fbaeb47#diff-af6acf848ee58d3419c6285d305c1602R690

2015-06-04 9:49 GMT+02:00 Karel Suta <notifications@github.com>:

**Comment by sutaakar** [comment]
Hi Maciej,

in that commit there was added sorting just for Process Definitions retrieval with filter parameter. See:
https://github.com/droolsjbpm/droolsjbpm-integration/blob/605847a14e6fc3634c341020d89ac5b23fbaeb47/kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm/src/main/java/org/kie/server/remote/rest/jbpm/RuntimeDataResource.java#L293
https://github.com/droolsjbpm/droolsjbpm-integration/blob/605847a14e6fc3634c341020d89ac5b23fbaeb47/kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm/src/main/java/org/kie/server/remote/rest/jbpm/RuntimeDataResource.java#L298

**Comment by mswiderski** [comment]
ah, now I got it, I missed one method in the change set. thanks will merge
it today

2015-06-04 12:08 GMT+02:00 Karel Suta <notifications@github.com>:

**Comment by mswiderski** [comment]
merged into execution server unification2 branch, thanks @sutaakar

**Pull request closed without merging**
