### PR TITLE
PLANNER-560 The score of the bestSolution is set before it is (fully)…

### PR DESCRIPTION
**Pull request by ge0ffrey**
… initialized, but from Solver.getBestSolution() it's not detectable that it's not yet initialized

Note: this doesn't fix the JAXB issue yet with marshalling the score, but it should fix the random failures of the testGetBestSolution() unit test.

### CODE REVIEW

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by mswiderski** [comment]
In general +1 , just asked jenkins to retest to see we don't have random failures

**Comment by mswiderski** [comment]
In general +1 , just asked jenkins to retest to see we don't have random failures

**Comment by ge0ffrey** [comment]
Agreed, I was also going to ask Jenkins to retest for random failures. We should probably ask it at least 3 times.

I looks like it just failed, but was a Jenkins problem, nothing to do with this change: "Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact org.dashbuilder:dashbuilder-bom:pom:0.5.0-SNAPSHOT in jboss-public-repository-group (https://repository.jboss.org/nexus/content/groups/public/)"

**Comment by ge0ffrey** [comment]
Jenkins retest this

**Comment by ge0ffrey** [comment]
Success.

Jenkins retest this again.

**Comment by ge0ffrey** [comment]
Build 353 also green.

Jenkins retest this.

**Comment by ge0ffrey** [comment]
354 also green.

@mswiderski I think it's ready to merge

**Pull request merged**
