### PR TITLE
JBPM-4812 - Allow to query by task variables (using the Query API)

### PR DESCRIPTION
**Pull request by mrietveld**
Depends on: 
- https://github.com/droolsjbpm/droolsjbpm-knowledge/pull/105
- https://github.com/droolsjbpm/jbpm/pull/325

Needed by: 
- (nothing)

### CODE REVIEW

**Comment by mrietveld** [comment]
@mswiderski Please check.

**Comment by mswiderski** [comment]
@mrietveld would be possible to add a test or will that test be more for kie-tests repository? besides looks ok, will merge locally and run all the tests as we have 3 repositories dependency

**Comment by psiroky** [comment]
@mswiderski the Jenkins build should now take all the dependent PRs and build them before this repo. If you believe the build should not have failed (I see test failures and compilation failure there), please let me know as it is likely a bug in the PR automation.

**Comment by mswiderski** [comment]
@psiroky I believe it did not take the all repos into account as there are failures referring to classes that are in jbpm repo though they cannot be found here. I'll confirm by running all locally to make sure it's not something else, will post my findings here

**Comment by psiroky** [comment]
The build used `git://github.com/mrietveld/jbpm:pr-JBPM-4812-marco` so that should be fine. I will re-trigger the build, just in case it picked-up some stale content on that branch.

**Comment by psiroky** [comment]
jenkins, retest this

**Comment by mrietveld** [comment]
@mswiderski There are no real changes here, see ([the real changes](https://github.com/droolsjbpm/droolsjbpm-integration/pull/221/files?w=1) here. Existing tests cover everything. 

The only real changes here are adding `TaskVariableImpl` to the `persistence.xml` and that the command name has changed (`TaskQueryWhereCommand` --> `TaskSummaryQueryCommand`).

**Comment by mrietveld** [comment]
ARGGHH... we have to update the other persistence.xml files with `TaskVariableImpl`, because the listener you created is being automatically registered. 

@mswiderski Is the task variable listener meant to be automatically registered? If so, then I can modify the `persistence.xml` files.

**Comment by mswiderski** [comment]
yes, it is automatically registered as this is the same listener that populates AuditTaskImpl and TaskEvents. I thought I updated all persistence.xml in my commit and ran all tests that were enabled ... though might have missed some

**Comment by mrietveld** [comment]
Okay, I'll update the PR so that these `persistence.xml` files are also fixed. 

I guess we might also need to look at jbpm-console-ng?

**Comment by mswiderski** [comment]
correct, once we agree to merge this jbpm console and kie-wb/kie-drools-wb will need to be updated as well. Will prepare PR for this as I will test this on workbenches as well before final push.

**Comment by mswiderski** [comment]
ah I think I know what's the issue, this PR (commit) should be on top of this one https://github.com/droolsjbpm/droolsjbpm-integration/pull/216 and it apparently it is not and thus it fails the build. 

@psiroky @mrietveld why would you say I merge them locally and submit as new PRs that includes all changes - applies to all three repos for consistency?

**Comment by psiroky** [comment]
@mswiderski fine with me.

**Comment by mrietveld** [comment]
@mswiderski +1 

Whatever is easiest. :)

**Comment by mswiderski** [comment]
closing as new PR including all changes will be submitted

**Pull request closed without merging**
