### PR TITLE
droolsjbpm-integration-tests module temporarily disabled in build.

### PR DESCRIPTION
**Pull request by tarilabs**
for master upstream

### CODE REVIEW

**Comment by psiroky** [comment]
+1

**Comment by mswiderski** [comment]
is this still valid?

**Comment by tarilabs** [comment]
I believe the related #648 was merged to allow _publishing_ (staging) for the 6.5.x branch. That was okay.
This is the analogous PR, but for master branch.
So far I don't think there is a solution to the `nexus-staging-maven-plugin` rule issue (will fwd you related email conversation).
I am okay to move this module somewhere else, as long as it will be under CI.
Please let me know, in case. Thx.

**Comment by mswiderski** [comment]
jenkins retest this
let's rerun the test and once successful we should merge it then, thanks for explanation @tarilabs

**Comment by tarilabs** [comment]
before merging I'd like to know where to move the module instead please :)

**Comment by psiroky** [comment]
@tarilabs I really don't know :)

**Comment by mswiderski** [comment]
since this module contains only jbpm related JMX test (https://github.com/droolsjbpm/droolsjbpm-integration/blob/master/droolsjbpm-integration-tests/src/test/java/org/drools/droolsjbpm/integrations/tests/MBeansMonitoringWithJBpmTest.java) I'd suggest to move it to jbpm-test-coverage instead.

Initially I thought there will be much more tests that requires access to droolsjbpm-integration module but it does seem like it (at least now)

**Comment by tarilabs** [comment]
Closed as superseeded by

- https://github.com/droolsjbpm/jbpm/issues/615
- https://github.com/droolsjbpm/droolsjbpm-integration/issues/669

**Pull request closed without merging**
