### PR TITLE
JBPM-5403: work item for per process instance test coverage

### PR DESCRIPTION
**Pull request by sutaakar**
Contains partial fix - fixed getWorkItem() functionality.
Minor refactoring to avoid duplicities.

### CODE REVIEW

**Comment by mswiderski** [comment]
@sutaakar I think the other case - when per process instance throws the SessionNotFound for context error we should transform it to ProcessInstanceNotFound exception

let me know if you'd like to take care of that too in jbpm services

**Comment by sutaakar** [comment]
@mswiderski I will try to take care about that

**Comment by mswiderski** [comment]
jenkins retest this

**Comment by mswiderski** [comment]
jenkins retest this

**Comment by mswiderski** [comment]
@sutaakar I believe we are good with this to be merged after your improvements in jbpm that were already merged, correct?

**Comment by sutaakar** [comment]
@mswiderski Right.

**Pull request merged**
