### PR TITLE
kie-remote-client: 'better' fix for parallel builds

### PR DESCRIPTION
**Pull request by psiroky**
@mswiderski this what we were talking about yesterday. The same is on 6.2.x already.

### CODE REVIEW

**Comment by mrietveld** [comment]
Huh.. how did this end up being provided in the first place?!?!?

**Comment by psiroky** [comment]
@mrietvel I did that some time ago :)

**Comment by mswiderski** [comment]
+1

**Comment by mrietveld** [comment]
Ah. :) +1

**Pull request closed without merging**
