### PR TITLE
JBPM-5026 - Not possible to change UserInfo in KieServer - add test

### PR DESCRIPTION
**Pull request by jakubschwan**

### CODE REVIEW

**Comment by mswiderski** [comment]
I believe this is going to fail some tests due to added new process definition to definition-project and there are few tests that checks how many and what processes are in the container that represents this project when deployed to kie server. but let's wait for jenkins to confirm or deny :)

**Comment by mswiderski** [comment]
@jakubschwan could you please fix the failing tests and rebase on master?

**Comment by jakubschwan** [comment]
@mswiderski fixed failing tests

**Comment by mswiderski** [comment]
test failure seems not related, though it can't be merged anymore. @jakubschwan could you please rebase it on master so I can merge it?

**Comment by jakubschwan** [comment]
@mswiderski conflicts fixed, can be merged now

**Comment by mswiderski** [comment]
excellent, thanks @jakubschwan

**Pull request merged**
