### PR TITLE
[6.5.x] kie-server-tests: Reset class loader before failing maven build

### PR DESCRIPTION
**Pull request by sutaakar**
Cherrypick of https://github.com/droolsjbpm/droolsjbpm-integration/pull/772
Affects just tests.

### CODE REVIEW

**Comment by mswiderski** [comment]
jenkins retest this

**Comment by psiroky** [comment]
jenkins retest this

**Comment by mswiderski** [comment]
jenkins retest this

**Comment by sutaakar** [comment]
jenkins retest this

**Pull request merged**
