### PR TITLE
BZ-1281549 - KIE Server: jBPM extension ignore runtime strategy (and …

### PR DESCRIPTION
**Pull request by mswiderski**
…other settings) from deployment descriptor included in kjar

(cherry picked from commit bee00cf897f0c047786a7d2620f6b08fb93d5a4f)

### CODE REVIEW

**Comment by etirelli** [comment]
jenkins retest this

**Comment by etirelli** [comment]
@mswiderski code looks good, but jenkins failed first build. trying again. +1 to merge if jenkins succeed.

**Comment by mswiderski** [comment]
this was caused by failure in jbpm (my fault wrong cherry pick) and thus this failed.
jenkins retest this

**Comment by mswiderski** [comment]
jenkins retest this

**Comment by mswiderski** [comment]
jenkins retest this

**Pull request merged**
