### PR TITLE
[6.5.x] Backport of various fixes from master

### PR DESCRIPTION
**Pull request by mswiderski**
@sutaakar @jakubschwan could you please check it out if I missed/wrongly merged as there were quite few test refactoring on kie server side, thanks

### CODE REVIEW

**Comment by sutaakar** [comment]
I noticed one thing.... I didn't find here https://issues.jboss.org/browse/JBPM-5083. Should it be backported too?

**Comment by mswiderski** [comment]
yes, I believe it would make sense to be included

**Comment by sutaakar** [comment]
Found one more fix to be backported: https://issues.jboss.org/browse/JBPM-5098 .

**Comment by mswiderski** [comment]
@sutaakar are we missing anything or we good to merge this one?

**Comment by sutaakar** [comment]
I think we are good to merge. If we will find anything missing we can add it later.

**Comment by mswiderski** [comment]
merged manually

**Pull request closed without merging**
