### PR TITLE
[6.5.x] kie-server-tests: improve findProcessInstances tests

### PR DESCRIPTION
**Pull request by sutaakar**
cherrypick of https://github.com/droolsjbpm/droolsjbpm-integration/pull/612

### CODE REVIEW

**Comment by mswiderski** [comment]
@sutaakar could you please double check the test failures as they seem to be related

**Comment by sutaakar** [comment]
Weird. I tried that locally and it passed.
Will check it tomorrow.

**Comment by mswiderski** [comment]
jenkins retest this

**Comment by sutaakar** [comment]
jenkins retest this

**Comment by sutaakar** [comment]
jenkins retest this

**Comment by sutaakar** [comment]
Removed checks for completed process instances as they didn't have much value in current implementation. Refactoring for proper use of completed process instances check became tricky as EAP6.4 has problem sending large JMS message (like message with 30+ completed processes).

**Comment by sutaakar** [comment]
jenkins retest this

**Comment by livthomas** [comment]
Jenkins retest this, we need this fix in order to be able to merge #598.

**Comment by mswiderski** [comment]
jenkins retest this

**Comment by mswiderski** [comment]
+1 to merge

**Pull request merged**
