### PR TITLE
DROOLS-719 - added Cargo WAS profile for Kie server

### PR DESCRIPTION
**Pull request by sutaakar**
Cherrypick of https://github.com/droolsjbpm/droolsjbpm-integration/pull/265 for 6.3.x.

### CODE REVIEW

**Comment by mswiderski** [comment]
+1

@etirelli @krisv since this is for 6.3.x I'd like to confirm it's ok. this affects only tests and will allow QE to automate WAS tests so in my opinion it's more than worth it

**Comment by psiroky** [comment]
+1 as well, affects only configuration and tests (and the CI build verified nothing breaks)

**Comment by etirelli** [comment]
+1, test changes are fine.

**Comment by mswiderski** [comment]
merged into 6.3.x, thanks @sutaakar

**Pull request closed without merging**
