### PR TITLE
DROOLS-733 - WebLogic test integration profile

### PR DESCRIPTION
**Pull request by sutaakar**
Changed controller URL as there cannot be 2 servlets with same url-pattern (also aligned to URL used in business central controller).

Please try it.
Ideas/improvements are welcome.

For running WebLogic profile you need to declare just profile and weblogic home, i.e.:
mvn clean install -Poracle-wls-12 -Dweblogic.home=/home/ksuta/wls/wls12130

### CODE REVIEW

**Comment by mrietveld** [comment]
Does this only impact the execution-server?

**Comment by mswiderski** [comment]
yes, this is only for kie server

**Comment by psiroky** [comment]
Yes, only kie-server for now. Once we tweak the configs and make sure everything is stable, we will do the same for kie-wb and kie-drools-wb as well.

**Comment by mrietveld** [comment]
Okay, when you tweak the `kie-wb` and `kie-drools-wb`, please (obviously :) ) make sure that both the exec-server and workbench REST services work with the new configuration. Thanks!

**Comment by psiroky** [comment]
@mrietveld just to clarify, we will probably need to tweak the Cargo config. There are no plans to touch the exec-server or workbech REST configs. I am assuming they are already work on WebLogic as they are being tested there.

Main purpose of these Cargo changes is to simplify the (local) testing on WebLogic.

**Comment by mrietveld** [comment]
Ahh.. okay, thanks!

**Pull request closed without merging**
