### PR TITLE
[6.4.x] JBPM-5277 - getTasksAssignedAsPotentialOwner doesn't allow groups searching, only actorid

### PR DESCRIPTION
**Pull request by livthomas**
This fixes the problem with the list of accepted commands which was not updated before and causes fails of all requests with `GetTasksByGroupCommand`.

### CODE REVIEW

**Comment by livthomas** [comment]
It seems that this fixes the problem only partially.

**Comment by mswiderski** [comment]
+1 to merge

could you please back port this to 6.5.x and master?

**Comment by mswiderski** [comment]
@livthomas reading your comment - are you still working on the other part or need help with it? I'll wait with merge for now...

**Comment by mswiderski** [comment]
@livthomas I believe you need to add it here as well https://github.com/livthomas/droolsjbpm-integration/blob/e86ee5803da4ba95ba95ee14af96cd0632ae35b9/kie-remote/kie-remote-client/src/main/java/org/kie/remote/client/jaxb/JaxbCommandsRequest.java#L129

**Comment by triceo** [comment]
Although it would not be trivial, a test could be written to make sure that the two places contain the same elements. This seems to me like a major potential source of bugs.

**Comment by livthomas** [comment]
@mswiderski I have added it to some other places where it should be but I need to test it in Business Central in order to verify it really works.

@triceo Actually, it is much more complicated as you can see from the latest fix.

**Comment by livthomas** [comment]
I have just tested it in Business Central and it works.

**Comment by mswiderski** [comment]
@livthomas could you please create PRs for upper branches?

**Comment by livthomas** [comment]
@mswiderski Sure, I am working on it.

**Pull request merged**
