### PR TITLE
kie-server-tests: enable custom settings.xml when building kjars for testing

### PR DESCRIPTION
**Pull request by psiroky**
* the settings.xml file can be used to define additional repos
   to download artifacts from (e.g. when testing staged build)

@mswiderski, @sutaakar please review

### CODE REVIEW

**Comment by mswiderski** [comment]
looks good to me (though haven't executed tests with it)

**Comment by sutaakar** [comment]
Looks good to me too (didn't try it yet either).

Just one small idea, any special reason to define default value for build settings parameter? You may use constructor without default value - default will be null then.

**Comment by psiroky** [comment]
The only reason was that I don't like `null`s :) But looking at the other config options now, they are not using any default value, so I will fix that to make it consistent. Thanks for pointing this out!

**Comment by psiroky** [comment]
Fixed - using the constructor without default value.

**Comment by mswiderski** [comment]
thanks, I'll merge locally and retest all before push

**Pull request closed without merging**
