### PR TITLE
BZ-1321576 - test improvement

### PR DESCRIPTION
**Pull request by sutaakar**
6.4.x cherrypick of https://github.com/droolsjbpm/droolsjbpm-integration/pull/388

### CODE REVIEW

**Comment by mswiderski** [comment]
jenkins retest this

**Comment by sutaakar** [comment]
jenkins retest this

**Comment by sutaakar** [comment]
jenkins retest this

**Comment by mswiderski** [comment]
+1 to merge

**Comment by mswiderski** [comment]
merged into 6.4.x, thanks @sutaakar

**Pull request closed without merging**
