### PR TITLE
kie-spring: improved PessimisticLockingSpringTest to handle different transaction timeouts

### PR DESCRIPTION
**Pull request by sutaakar**
Improved PessimisticLockingSpringTest to work against different databases. Can handle case when transaction timeout is set to 0, to value smaller or bigger than waiting time between start of thread 2 and commit in thread 1.
Method getProcessInstance in thread 2 is set to be read only to differentiate from cases when pessimistic locking is turned off - in which case process instance is returned immediately. Invoking method abortProcessInstance(in previous test version) contains writing to database which causes waiting on thread 1 to unlock affected rows even if pessimistic locking is turned off.

### CODE REVIEW

**Comment by mswiderski** [comment]
overall looks good, just one thing that I think we don't need:
> Method getProcessInstance in thread 2 is set to be read only to differentiate from cases when pessimistic locking is turned off - in which case process instance is returned immediately.

since this test is explicitly for pessimistic lock testing don't think we should add anything that allows to run it without pessimistic lock being configured. If we want that then test should be renamed and both optimistic and pessimistic lock test methods should be implemented. Wdyt?

**Comment by sutaakar** [comment]
That comment was meant as explanation why I set read-only flag in getProcessInstance method. Without it test would behave same for both types of locking and we wouldn't be able to verify that pessimistic locking is really set.
Test is done just for pessimistic locking, with optimistic locking it will fail.

**Comment by mswiderski** [comment]
understood, will merge this later today. thanks @sutaakar

**Comment by mswiderski** [comment]
merged into master https://github.com/droolsjbpm/droolsjbpm-integration/commit/b0ecce1e6fdd0bd973256abf8626140973faee76

**Pull request closed without merging**
