### PR TITLE
squid:S1118 - Utility classes should not have public constructors

### PR DESCRIPTION
**Pull request by georgekankava**
This pull request is focused on resolving occurrences of Sonar rule
squid:S1118 - Utility classes should not have public constructors.
You can find more information about the issue here:
https://dev.eclipse.org/sonar/rules/show/squid:S1118
Please let me know if you have any questions.
George Kankava

### CODE REVIEW

**Comment by psiroky** [comment]
ok to test

**Comment by mswiderski** [comment]
build failure is related to this PR, @georgekankava could you please check it?

**Comment by mswiderski** [comment]
any update on this or shall we close?

**Comment by georgekankava** [comment]
I will take a look at it. Thanks 

Get Outlook for iOS




On Mon, Jul 11, 2016 at 3:36 PM +0400, "Maciej Swiderski" <notifications@github.com> wrote:












any update on this or shall we close?

**Comment by georgekankava** [comment]
@mswiderski Unfortunately Jenkins server is unreachable. I was not able to check errors. I will close this PR.

**Pull request closed without merging**
