### PR TITLE
Reorganize imported BOMs to avoid unnecessary dependencies

### PR DESCRIPTION
**Pull request by psiroky**
@mbiarnes @mariofusco this should in theory fix the issues with the OSGi blueprint test failures.

### CODE REVIEW

**Comment by psiroky** [comment]
The failinig tests are currently failing also on vanilla master.

**Comment by mswiderski** [comment]
I am going to look at this failing tests

**Comment by mbiarnes** [comment]
+1 (let's wait what @mswiderski says)

**Comment by mswiderski** [comment]
mswiderski says +1 :)

**Pull request merged**
