### PR TITLE
[DROOLS-729] fixed android examples

### PR DESCRIPTION
**Pull request by kedzie**
Im pushing a new PR which fixes all the examples.. you guys can decide what to do about the remaining 3rd party deps...

* I added back the harmony-beans jar (we can make a new one if you think it is missing classes, i'm not sure)
* I added a javax.naming-jndi-1.3 jar. I made it by taking classes from openJDK. I had to do this because the CDIHelper class (which attaches listeners to a session) references it, even if it isn't used it needs to be there or I get a VerifyError on the class.. so I had to add this.. kinda sucks but it is the case.

### CODE REVIEW

**Comment by mrietveld** [comment]
@kedzie Thank you for patience and cooperation with @psiroky 

BTW, http://www.infoq.com/news/2015/09/MobileOpenJDK -- which is part of why this is important.

**Comment by psiroky** [comment]
I have this PR on my TODO list, but it is by far not as easy as it may seem. We can't simply take parts of JDK classes, bundle them into jar and start using it. The dependency needs to be in some remote repository we use. In ideal case we would just reuse existing dependency, but there seems to be none that suits the purpose. So unless there is some better workaround, we will need to make sure (licensing) we can grab subset of classes from JDK, bundle them into jar and upload them into our JBoss.org repo.

I would also like to avoid the dependency on the Java beans altogether, by fixing core Drools to not use classes from java.beans package.

**Comment by mrietveld** [comment]
+1 on not using the java.beans classes.

**Comment by kedzie** [comment]
That would be great.. i know there is an openbeans that could be used instead..  the main reason java beans is used is for sessions to subscribe to property change events and re-fire the rules.

**Comment by mswiderski** [comment]
closing as it did not have any attention for a while and can't be merged due to conflicts, feel free to reopen

**Comment by kedzie** [comment]
I worked hard on this, the problem was the java.beans depedency, which
isn't part of the android java sdk.

**Comment by kedzie** [comment]
Nobody agreed to deploy our own version to the maven repo, which left this
android functionality not functional.

On Mon, Aug 15, 2016 at 1:55 PM, Marek Kedzierski <mark.kedzierski@gmail.com
> wrote:

> I worked hard on this, the problem was the java.beans depedency, which
> isn't part of the android java sdk.
>
> On Wed, Aug 10, 2016 at 2:36 AM, Maciej Swiderski <

**Comment by psiroky** [comment]
The dependency tree for drools-android is quite a mess (I am not blaming anyone here, it's just how it is with the Android). The current integration should still work assuming one would add their own dependency with java.beans package -- I agree this is far from ideal. It should just work OOTB.

I am quite against deploying custom, hand-made jars, with no sources and with no way to make the build reproducible (yes, I am build guy as well and this has bitten few times in the past)

The proper solution is to remove the java.beans need from the Drools core itself. However, that is also a bigger task.

I've also spent quite a few hours on this, trying to find alternative solutions, reviewing, etc. I will give this one more shot in the near (few weeks) future to see what we can do to make this work and to not waste the effort that was put into this by @kedzie.

**Comment by kedzie** [comment]
Could replace with openbeans?   Problem though is that I imagine there are
existing users which utilize the property change listener support.  The
session registers itself for property change events from the java beans and
re fires the rules when properties change.

**Comment by psiroky** [comment]
Yes, that is one possibility, but we will need to evaluate what exactly will get broken if we change the package name as openbeans uses different packages (we can in theory break backwards compatibility for 7.x, if there is no other way around...).

I would also like to take a look at removing the usage of java.beans as that would basically fix this problem once and for all. Will keep you posted..

**Comment by psiroky** [comment]
So I got a bit further with this. I believe I was able to fix the `java.beans` issue with this commit:
https://github.com/droolsjbpm/drools/commit/a8282e5d5446524aff9abd97193e346cebbcd512

To make it even more complicated, Android (or the tooling around) does not support Java 8 class files (bytecode version 52), so I had to revert to work on 6.5.x.

I am now getting this error after launching the app (I had to change the `<platform>21</platform>` to `<platform>24</platform>` since 21 was not working for some reason):
```
08-25 17:46:15.474  2948  2948 W art     : Unexpected CPU variant for X86 using defaults: x86_64
08-25 17:46:15.551  2948  2948 W System  : ClassLoader referenced unknown path: /data/app/org.drools.examples.android.kiecontainer-1/lib/x86_64
08-25 17:46:15.567  2948  2948 I MultiDex: VM with version 2.1.0 has multidex support
08-25 17:46:15.567  2948  2948 I MultiDex: install
08-25 17:46:15.567  2948  2948 I MultiDex: VM has multidex support, MultiDex support library is disabled.
08-25 17:46:15.755  1218  1968 E BufferQueueProducer: [com.android.launcher3/com.android.launcher3.Launcher] cancelBuffer: slot 0 is not owned by the producer (state = QUEUED)
08-25 17:46:15.760  2948  2948 E System  : Ignoring attempt to set property "java.version" to value "1.6".
08-25 17:46:15.761  2948  2948 W System  : ClassLoader referenced unknown path: /data/user/0/org.drools.examples.android.kiecontainer/cache/drools/dex/temp.dex
08-25 17:46:15.761  2948  2948 W System  : ClassLoader referenced unknown path: /data/app/org.drools.examples.android.kiecontainer-1/lib/x86_64
08-25 17:46:15.763  2948  2963 D org.drools.examples.android.DroolsActivity: Loading Classpath container
08-25 17:46:15.764  2948  2963 I org.drools.compiler.kie.builder.impl.ClasspathKieProject: Found kmodule: jar:file:/data/app/org.drools.examples.android.kiecontainer-1/base.apk!/META-INF/kmodule.xml
08-25 17:46:15.765  2948  2963 D org.drools.compiler.kie.builder.impl.ClasspathKieProject: KieModule URL type=jar url=/data/app/org.drools.examples.android.kiecontainer-1/base.apk
08-25 17:46:15.822  1218  1581 E SurfaceFlinger: ro.sf.lcd_density must be defined as a build property
08-25 17:46:16.118  2948  2963 D org.drools.compiler.kie.builder.impl.ClasspathKieProject: Found and used pom.properties META-INF/maven/org.drools/kiecontainer/pom.properties
08-25 17:46:16.169  2948  2963 D org.drools.compiler.kie.builder.impl.ClasspathKieProject: Discovered classpath module org.drools:kiecontainer:6.5.0-SNAPSHOT
08-25 17:46:16.175  2948  2963 I org.drools.compiler.kie.builder.impl.KieRepositoryImpl: KieModule was added: ZipKieModule[releaseId=org.drools:kiecontainer:6.5.0-SNAPSHOT,file=/data/app/org.drools.examples.android.kiecontainer-1/base.apk]
08-25 17:46:16.237  2964  2964 W RenderThread: type=1400 audit(0.0:12): avc: denied { search } for name="graphics" dev="tmpfs" ino=3303 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:graphics_device:s0 tclass=dir permissive=0
08-25 17:46:16.243  2948  2964 D OpenGLRenderer: Swap behavior 1
08-25 17:46:16.340  2948  2963 W System  : ClassLoader referenced unknown path: /data/user/0/org.drools.examples.android.kiecontainer/cache/drools/dex/temp.dex
08-25 17:46:16.340  2948  2963 W System  : ClassLoader referenced unknown path: /data/app/org.drools.examples.android.kiecontainer-1/lib/x86_64
08-25 17:46:16.356  2948  2953 I art     : Do partial code cache collection, code=24KB, data=29KB
08-25 17:46:16.357  2948  2953 I art     : After code cache collection, code=23KB, data=29KB
08-25 17:46:16.357  2948  2953 I art     : Increasing code cache capacity to 128KB
08-25 17:46:16.358  2948  2963 W System  : ClassLoader referenced unknown path: /data/user/0/org.drools.examples.android.kiecontainer/cache/drools/dex/temp.dex
08-25 17:46:16.358  2948  2963 W System  : ClassLoader referenced unknown path: /data/app/org.drools.examples.android.kiecontainer-1/lib/x86_64
08-25 17:46:16.383  2948  2963 E org.drools.android.MultiDexClassLoader: Errorjava.lang.IllegalAccessException: java.lang.Class<dalvik.system.DexPathList> is not accessible from java.lang.Class<org.drools.android.MultiDexClassLoader>
08-25 17:46:16.383  2948  2963 E org.drools.android.MultiDexClassLoader: 	at java.lang.reflect.Constructor.newInstance0(Native Method) ~[na:0.0]
08-25 17:46:16.383  2948  2963 E org.drools.android.MultiDexClassLoader: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:430) ~[na:0.0]
08-25 17:46:16.383  2948  2963 E org.drools.android.MultiDexClassLoader: 	at org.drools.android.MultiDexClassLoader.defineClass(MultiDexClassLoader.java:125) ~[na:0.0]
08-25 17:46:16.383  2948  2963 E org.drools.android.MultiDexClassLoader: 	at org.drools.android.MultiDexClassLoader.defineClass(MultiDexClassLoader.java:140) ~[na:0.0]
08-25 17:46:16.383  2948  2963 E org.drools.android.MultiDexClassLoader: 	at org.drools.core.base.ClassFieldAccessorFactory.getClassFieldReader(ClassFieldAccessorFactory.java:115) ~[na:0.0]
08-25 17:46:16.383  2948  2963 E org.drools.android.MultiDexClassLoader: 	at org.drools.core.base.ClassFieldAccessorCache$CacheEntry.getReadAccessor(ClassFieldAccessorCache.java:178) ~[na:0.0]
08-25 17:46:16.383  2948  2963 E org.drools.android.MultiDexClassLoader: 	at org.drools.core.base.ClassFieldAccessorCache.getReadAcessor(ClassFieldAccessorCache.java:95) ~[na:0.0]
08-25 17:46:16.383  2948  2963 E org.drools.android.MultiDexClassLoader: 	at org.drools.core.base.ClassFieldAccessorStore.wire(ClassFieldAccessorStore.java:303) ~[na:0.0]
08-25 17:46:16.383  2948  2963 E org.drools.android.MultiDexClassLoader: 	at org.drools.core.base.ClassFieldAccessorStore.getAccessor(ClassFieldAccessorStore.java:193) ~[na:0.0]
``` 

It boils down to `java.lang.Class<dalvik.system.DexPathList> is not accessible from java.lang.Class<org.drools.android.MultiDexClassLoader>`. Looks like the internal Android API changed. @kedzie any hints on how to properly fix this?

**Comment by psiroky** [comment]
I've merged the changes from this PR into master and 6.5.x branches (with some minor fixes).

There are currently outstanding issues:

 * the above mentioned exception, which prevents the compilation of rules
 * the kie-maven-plugin's goal `serialized` no longer works for some reason, needs to be investigated

**Pull request closed without merging**
