### PR TITLE
kie-remote-client: 'better' fix for parallel builds

### PR DESCRIPTION
**Pull request by psiroky**
@mswiderski this what we were talking about yesterday. The same is on 6.2.x already.

### CODE REVIEW

**Comment by mswiderski** [comment]
+1

**Comment by mrietveld** [comment]
@psiroky @mswiderski Just to be clear: kie-remote-jaxb-gen should ****NEVER**** be exposed to users or anyone. It is an INTERNAL hack and should NOT be available via nexus.

**Comment by psiroky** [comment]
@mrietveld I wasn't aware of that. It is currently build and deployed as any other module, so you will find it in nexus.

**Comment by mswiderski** [comment]
@psiroky shall this go to 6.3.x considering we are in blockers only mode?

**Comment by psiroky** [comment]
It does not change the code itself and is only build-related. So I would vote for yes.

**Comment by mswiderski** [comment]
merged, thanks

**Pull request closed without merging**
