### PR TITLE
Added test for kie-maven-plugin that reproduces problem with 2 DSL files. 

### PR DESCRIPTION
**Pull request by baldimir**
Please **DO NOT MERGE** now. We need to discuss a solution for this problem with @mariofusco and @etirelli before merging. 

This is a reproducer extracted from issue reported by @tkobayas on support mailinglist. Thanks @tkobayas!

### CODE REVIEW

**Comment by mswiderski** [comment]
this is green (including tests) is it waiting for anything or can be merged or closed?

**Comment by etirelli** [comment]
I believe @mariofusco already worked on this and solved it? @mariofusco can you please confirm?

**Comment by mswiderski** [comment]
@mariofusco any update what to do with this PR?

**Comment by mariofusco** [comment]
@etirelli @mswiderski The test is green only for a lucky coincidence. The problem is in the fact that when you have more than one DSL file the order in which you process them matters, but at the moment if those DSL are in the same project you don't have any control on that order. One possible solution would be allowing to declare inside the pom the order in which DSL files have to be processed. However we decided to not do this for now and just suggested to keep all DSL statements belonging to the same area in the same file, so to have control on their order.

**Pull request closed without merging**
