### PR TITLE
Additional setters in FactoryBeans to fix IDE (Eclipse/Spring) errors

### PR DESCRIPTION
**Pull request by 7Bit**
If you use Eclipse with m2e and Spring support, and are adding the kie-spring dependency to your project, you are experiencing errors in the Spring Bean definitions of the knowledge bases, as you can read here:
https://lists.jboss.org/pipermail/rules-users/2014-April/035762.html
http://drools-moved.46999.n3.nabble.com/Kie-namespace-td4030236.html

If you add additional setters with a slighty modified syntax, the IDE errors are gone.

### CODE REVIEW

**Comment by psiroky** [comment]
The PR is quite old, are those changes still relevant?

**Comment by mrietveld** [comment]
@psiroky +1 for merging -- the changes can't do any harm and it looks like solve a minor problem. 

(Maybe add a comment to the methods mentioning that they solve "Eclipse with m2e and Spring support" errors?)

**Comment by 7Bit** [comment]
As far as I know these changes are still relevant. Can't verify it though, we decided not to use the Spring integration.

**Comment by psiroky** [comment]
Merged into master as https://github.com/droolsjbpm/droolsjbpm-integration/commit/47b5296f3bb25848dd9fb2b897544d4f19415159. Thanks for the PR!

**Pull request closed without merging**
