### PR TITLE
[6.5.x] RHBPMS-4098 - Process Instance Halting Mid Process

### PR DESCRIPTION
**Pull request by mswiderski**
(cherry picked from commit 649142980081c2c0a63a07fa98937aac25fca004)

### CODE REVIEW

**Comment by mswiderski** [comment]
jenkins retest this

**Comment by mswiderski** [comment]
@psiroky @sutaakar any idea why these are failing to init?

**Comment by sutaakar** [comment]
@mswiderski It seems to be caused by SpreadsheetIntegrationTest. Looks like some recent change caused compilation issue in spreadsheet.

**Comment by mswiderski** [comment]
jenkins retest this

**Comment by mswiderski** [comment]
jenkins retest this

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by mswiderski** [comment]
Jenkins retest this

**Pull request merged**
