### PR TITLE
[6.5.x] kie-server-tests: fix response handler tests on slow databases

### PR DESCRIPTION
**Pull request by livthomas**
I have fixed some tests that caused problems on slower databases.

### CODE REVIEW

**Comment by livthomas** [comment]
@sutaakar, if you see test failures in our test suite, it is because of these tests.

**Comment by sutaakar** [comment]
Thanks for info.
Looks good.

**Comment by mswiderski** [comment]
@livthomas thanks, can we have this for master too?

**Comment by livthomas** [comment]
@mswiderski, yes, I will send a pull-request as soon as I run fixed tests on various databases and verify that there are no more failures.

**Pull request merged**
