### PR TITLE
[DROOLS-1452] fixes after Maven 3.2.5 -> 3.3.9 upgrade

### PR DESCRIPTION
**Pull request by psiroky**
Depends on https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/pull/401

### CODE REVIEW

**Comment by psiroky** [comment]
@mswiderski or @sutaakar could you please quickly review the kie-server changes?

**Comment by mswiderski** [comment]
looks ok to me, though would be worth trying this on WAS as I remember there were few issues with guide in there but that might have been related to workbench only.

**Comment by psiroky** [comment]
@mswiderski I am afraid I won't be able to try this on WAS.

**Comment by mswiderski** [comment]
@psiroky no worries, I just thought about this and soon we need to try this (kie server) out on all containers anyway so we fix anything related at that time

**Comment by mswiderski** [comment]
+1

**Pull request merged**
