### PR TITLE
RHBRMS-2547 Add exclusion for springwork.osgi since the transitive de…

### PR DESCRIPTION
**Pull request by ryanzhang**
…ps are invalid

This patch has been merged to jboss-integration/droolsjbpm-integration.(See https://github.com/droolsjbpm/droolsjbpm-integration/pull/593 )

This should also added into droolsjbpm/droolsjbpm-integration project.

### CODE REVIEW

**Comment by psiroky** [comment]
ok to test

**Comment by mswiderski** [comment]
how is this different from https://github.com/droolsjbpm/droolsjbpm-integration/pull/593

**Comment by psiroky** [comment]
@mswiderski good question :) I originally thought that the target branches are different, but now seeing that both target 6.5.x.

**Comment by ryanzhang** [comment]
Ah, my bad!
 I originally thought the #593 has been merged to jboss-integration/droolsjbpm-integration.
And this one is to PR to droolsjbpm/droolsjbpm-integration.

But you are right.  There is no difference.
I am closing this. Sorry for inconvinence.

**Pull request closed without merging**
