### PR TITLE
kie-server tests: refactored kie client

### PR DESCRIPTION
**Pull request by sutaakar**
Removed duplicities in creating client, simplified  configuration changes.

### CODE REVIEW

**Comment by sutaakar** [comment]
Adjusted to cover also OptaPlanner tests.

**Comment by mswiderski** [comment]
jenkins retest this

**Comment by sutaakar** [comment]
failure caused by https://github.com/droolsjbpm/droolsjbpm-integration/pull/328

**Comment by psiroky** [comment]
jenkins retest this

**Comment by mswiderski** [comment]
+1

**Pull request closed without merging**
