### PR TITLE
[6.3.x] KIE Server back ports for 6.2.x patch

### PR DESCRIPTION
**Pull request by mswiderski**
https://bugzilla.redhat.com/show_bug.cgi?id=1319548
https://bugzilla.redhat.com/show_bug.cgi?id=1315767

### CODE REVIEW

**Comment by mswiderski** [comment]
jenkins retest this

**Comment by mswiderski** [comment]
jenkins retest this

**Comment by psiroky** [comment]
The upstream for drools needs to be rebase on top on latest 6.3.x changes to fix the test here. This is known limitation of the PR builds (they just take the branch instead of merging it automatically with the latest changes on target branch).

**Comment by mswiderski** [comment]
jenkins retest this

**Comment by mswiderski** [comment]
aha and we're green now :) thanks @psiroky

**Comment by mswiderski** [comment]
pushed to 6.3.x branch

**Pull request closed without merging**
