### PR TITLE
JBPM-4806 Remove YamlRemoteSerializationTest and YAML dependencies from pom.xmls

### PR DESCRIPTION
**Pull request by baldimir**
- Removed 2 YAML tests
- Removed all references to yaml from pom.xmls

I removed YAML dependencies from 3 pom.xmls. Please verify if it's really not needed there. I ran clean install build on whole droolsjbpm-integration and the build passed (also with tests).

### CODE REVIEW

**Comment by mrietveld** [comment]
+1 please merge.

**Comment by mswiderski** [comment]
merged to master, in case it needs to be in 6.3.x let me know or drop another PR for 6.3.x branch

**Comment by mrietveld** [comment]
@mswiderski Please cherry-pick to 6.3.x.

**Comment by mswiderski** [comment]
@baldimir do you mind providing PR for 6.3.x branch?

**Comment by baldimir** [comment]
Yes, if it is needed, I'll make one today.

**Comment by baldimir** [comment]
PR for 6.3.x: https://github.com/droolsjbpm/droolsjbpm-integration/pull/211

**Pull request closed without merging**
