### PR TITLE
JBPM-4934 AuditService obtained from RuntimeEngine doesn't work with Local transacations

### PR DESCRIPTION
**Pull request by agiertli**

### CODE REVIEW

**Comment by psiroky** [comment]
ok to test

**Comment by psiroky** [comment]
@agiertli fyi, if you accept the invitation to droolsjbpm org. unit, your PRs will get a test build automatically.

**Comment by agiertli** [comment]
These are the unit tests for the fix which is part of different PR:

https://github.com/droolsjbpm/jbpm/pull/396

**Comment by agiertli** [comment]
The failed tests seems to be unrelated to the code changes done in this PR.

**Comment by mswiderski** [comment]
jenkins retest this

**Pull request closed without merging**
