### PR TITLE
PLANNER-505: initial implementation for the Optaplaner Kie Server Extension

### PR DESCRIPTION
**Pull request by etirelli**
Previous PR broke 6.4.x branch. Submitting it again.

### CODE REVIEW

**Comment by sutaakar** [comment]
Failures in QueryDataServiceIntegrationTest are unrelated to this commit. Will be solved in separate PR.

**Comment by etirelli** [comment]
OSGi tests fixed. All tests pass now. As soon as we get the +1, we can merge.

@sutaakar @mswiderski @ge0ffrey

**Comment by ge0ffrey** [comment]
+1

@sutaakar this doesn't include your PR test to my branch yet, but I am working on fixing that.

**Comment by sutaakar** [comment]
+1

**Comment by mswiderski** [comment]
+1 once the build completes successfully

**Comment by etirelli** [comment]
Since the query test failures are unrelated, I am merging this PR now.

**Comment by etirelli** [comment]
Merged.

**Pull request closed without merging**
