### PR TITLE
PLANNER-565 - Marshall best solution score test

### PR DESCRIPTION
**Pull request by sutaakar**
Showing issues described in referenced JIRA.

### CODE REVIEW

**Comment by mswiderski** [comment]
@ge0ffrey this looks like problem with*Score classes that cannot be properly marshaled as the fields are final and can be set only via constructor. This is not really valid for JAXB that uses either field access of setters. So if I am not mistaken this has to be changed on optaplanner side to be JAXB/JSON friendly - either by providing setters/getters or alternative way to be set - like JAXB adapters.

**Comment by ge0ffrey** [comment]
Ok, we need optaplanner-persistence-jaxb :)
btw, we already have optaplanner-persistence-xstream, but the exe server doesn't use it yet (it should)

**Comment by mswiderski** [comment]
@ge0ffrey are you going to build the optaplanner-persistence-jaxb module? Otherwise I don't think we have any option to solve these issues...

**Comment by ge0ffrey** [comment]
@mswiderski Yes - but it's currently not in my short time list and only aimed for 7.0. How high is the urgency on this?

**Comment by mswiderski** [comment]
@ge0ffrey I guess it's mainly up to you to asses as it might limit usage of optaplanner over kie server.

**Comment by mswiderski** [comment]
do we still need this/plan to merge?

**Comment by sutaakar** [comment]
Rebased to contain latest changes. There are still issues with JSON marshalling for bendable score. Should it be supported?

**Comment by ge0ffrey** [comment]
These tests should move into optaplanner-persistence-*, which contains already some:
there are already xstream and jaxb tests, for each score implementation.

JSON support for Score's is still an open issue...

**Comment by sutaakar** [comment]
Right, will prepare a PR there.

**Comment by ge0ffrey** [comment]
Interestingly enough, this one tests the marshalling of SolverInstance too. So this might prove or disprove PLANNER-604. SolverInstance is a Execution Server object, so we can't do that test in optaplanner core.

@sutaakar Karel, let's talk on irc/bluejeans about this PR and #425

**Comment by ge0ffrey** [comment]
Relates to PLANNER-612

**Comment by mswiderski** [comment]
any plans to merge this or...

**Comment by ge0ffrey** [comment]
Sorry Matej for losing track of this, thanks for the reminder. Looking at it.

**Comment by ge0ffrey** [comment]
jenkins retest this

**Comment by ge0ffrey** [comment]
This open PR from Jun with failing tests in Jun might now have green tests thanks to this merged PR from October:
  https://github.com/droolsjbpm/droolsjbpm-integration/pull/695/files

I still think that testing the different score types here is pointless (= maintenance), as we're already doing that in optaplanner-persistence for both XStream, JAXB and Jackson for each score type. for example:
  https://github.com/droolsjbpm/optaplanner/blob/master/optaplanner-persistence/optaplanner-persistence-jaxb/src/test/java/org/optaplanner/persistence/jaxb/api/score/buildin/hardsoft/HardSoftScoreJaxbXmlAdapterTest.java

However testing one SolverInstance with a HardScore marshaling/unmarshalling is probably useful to have 

@mcimbora Wdyt?

**Comment by sutaakar** [comment]
Refactored to check marshalling of SolverInstance with a HardSoftScore.

**Pull request merged**
