### PR TITLE
[BZ-1267510] maven-plugin: add additional converters to support guide…

### PR DESCRIPTION
**Pull request by psiroky**
…d dtables and score cards + small clean-up

 * guided rule templates, dtables and score cards are now supported by the plugin

### CODE REVIEW

**Comment by psiroky** [comment]
Related PRs:
https://github.com/droolsjbpm/droolsjbpm-knowledge/pull/103
https://github.com/droolsjbpm/drools/pull/521

**Comment by manstis** [comment]
BuildMojo adds Guided Score Cards twice and no Guided Decision Table.

**Comment by manstis** [comment]
Can we have tests for both a Guided Decision Table and Template with DSLS too? (accepting Templates may follow?

**Comment by psiroky** [comment]
I've fixed the typo with duplicated GuidedScoreCardsProvider. I will look into adding more tests as well.

**Comment by psiroky** [comment]
@mariofusco I am still working on this one. I will let you know (by commenting here) where everything is ready.

**Comment by psiroky** [comment]
I've added .gdst that uses DSL sentences. I will look into the templates tests when fixing this BZ https://bugzilla.redhat.com/show_bug.cgi?id=1266076 as I don't to want to hold off this PR anymore (it already contains quite a lot of changes).

**Comment by manstis** [comment]
"I don't to want to hold off this PR anymore (it already contains quite a
lot of changes)."

PRs get merged when the bug/feature is deemed "complete".. not because the
PR contains "..quite a lot of changes" ;)

**Comment by psiroky** [comment]
@manstis, true, but this PR isn't (and never was) about fixing compilation of templates with DSL. It was about making sure `kie-maven-plugin` contains all the necessary dependencies to build all the supported resources. That fix needs to be done directly in drools-core and there is different BZ for that: https://bugzilla.redhat.com/show_bug.cgi?id=1266076

**Comment by mariofusco** [comment]
Merged by https://github.com/droolsjbpm/droolsjbpm-integration/commit/48333a4525b82ff7a41000fefb295f18e32f7a46

**Pull request closed without merging**
