### PR TITLE
DROOLS-1222 - Upgrade kie-server from jackson 1 to jackson 2

### PR DESCRIPTION
**Pull request by mswiderski**
depends on https://github.com/droolsjbpm/jbpm/pull/736

### CODE REVIEW

**Comment by mswiderski** [comment]
@sutaakar would it be possible to run this on all containers to make sure it has no side effects?

**Comment by sutaakar** [comment]
@mswiderski Sure, will try it.

**Comment by sutaakar** [comment]
I have some issues with verification on WebSphere, will check that later this week.

**Comment by mswiderski** [comment]
@sutaakar any update on this?

**Comment by sutaakar** [comment]
@mswiderski looking on it right now

**Comment by sutaakar** [comment]
After applying https://github.com/droolsjbpm/droolsjbpm-integration/pull/811 and removing CDI [1] it passed on WebSphere (tried on jbpm integration tests)

[1] https://issues.jboss.org/browse/DROOLS-1426

**Comment by mswiderski** [comment]
#811 is now merged. Do we need to give a try on Weblogic again after the merge of #811?

**Comment by sutaakar** [comment]
I will make a brief check

**Comment by sutaakar** [comment]
WebLogic seems to work

**Comment by mswiderski** [comment]
so we are good to merge this as DROOLS-1426 is generic issue for WAS, correct?

**Comment by sutaakar** [comment]
Yes

**Pull request merged**
