### PR TITLE
BZ-1321790 Add OSGi features support for optaplanner-persistence-xstream

### PR DESCRIPTION
**Pull request by ge0ffrey**
(cherry picked from commit ca2c61944ed338dc8194e73ca3f5353979dc5811)

### CODE REVIEW

**Comment by ge0ffrey** [comment]
jenkins please retest this

**Comment by ge0ffrey** [comment]
jenkins test this

**Comment by ge0ffrey** [comment]
The Jenkins failed status is not correct. It's a bug on jenkins.

**Comment by mswiderski** [comment]
+1

**Pull request merged**
