### PR TITLE
Align reactivity support for Collection interfaces.

### PR DESCRIPTION
**Pull request by tarilabs**
Depends on droolsjbpm/drools#1033 .

### CODE REVIEW

**Comment by tarilabs** [comment]
```
Test Result (1 failure / +1)
org.kie.server.integrationtests.common.rest.RestMalformedRequestIntegrationTest.testCreateContainerNonExistingGAV2[JAXB]
```

Jenkins, test again :8ball:

**Comment by psiroky** [comment]
IMO we really should not merge PRs until they are "green". Without successful build, we can't be sure if the PR won't break the build.

**Comment by mswiderski** [comment]
+1 for this, without build results we can't asses the impact as well.

**Comment by tarilabs** [comment]
I agree but in this case the modification of all commits in the PR are affecting just the `kie-maven-plugin`
for bytecode instrumentation (with optional parameter to be set in order to "trigger" the feature) while the failed test:
```
org.kie.server.integrationtests.common.rest.RestMalformedRequestIntegrationTest.testCreateContainerNonExistingGAV2[JAXB]
```
is about the kie server.

The earlier commit a8f7ee3 is ticked green and subsequent d9688d1 is just a micro optimization pertaining the same scope (of the `kie-maven-plugin`) hence we agreed with @mariofusco to just merge anyway.

**Comment by psiroky** [comment]
I disagree. If the test is failing, then it needs to be fixed regardless if this PR is causing the fail or not. If you don't know how to fix it, then contact someone who can. If it is randomly failing then it needs to be stabilized. If wee keep doing this, the tests will never get stabilized.

**Pull request merged**
