### PR TITLE
[6.5.x] RHBPMS-4426 - KIE Server does not delete tasks of aborted processes, RHBPMS-4405 - Tasks Dashboard does not show tasks started on KIE Server

### PR DESCRIPTION
**Pull request by mswiderski**

### CODE REVIEW

**Comment by mswiderski** [comment]
updated PR to include https://issues.jboss.org/browse/RHBPMS-4405 as well

**Comment by livthomas** [comment]
@mswiderski, why are there changes in `QueryServicesClientImpl`?

**Comment by mswiderski** [comment]
it was required to test properly the addition of task bam listener. it did not work well with raw mapper.

**Comment by krisv** [comment]
+1

**Comment by mswiderski** [comment]
merged manually

**Pull request closed without merging**
