### PR TITLE
[DROOLS-1230] kie-server: EE7 WAR supports WFLY10/EAP7 by default (in…

### PR DESCRIPTION
**Pull request by psiroky**
…stead of WFLY8)

 * the included JMS config makes it impossible to make the WAR work on
   both WFLY8 and WFLY10 OOTB at the same time
 * the EE7 WAR should still work on WildFly 8, but the META-INF/kie-server-jms.xml needs
   to be manually fixed (e.g. replacing the new WFLY10/ActiveMQ config
   with the old WFLY8/HornetQ one)

### CODE REVIEW

**Comment by mswiderski** [comment]
@psiroky is this something environment specific or shall we try to retest this?

**Comment by psiroky** [comment]
@mswiderski definitely looks like related to these changes. It seems I messed up the JMS configs for EAP 6.4. Will take another look and fix it.

**Comment by psiroky** [comment]
Please hold on with this one. I found one more Cargo configuration issue for EAP7 (I will also make sure the tests pass locally with Tomcat 8, EAP 6.4, EAP7 and WildFly 10)

**Comment by psiroky** [comment]
This is now ready for review.

**Comment by mswiderski** [comment]
+1 to merge

**Comment by sutaakar** [comment]
+1

**Pull request merged**
