### PR TITLE
DROOLS-1384 - Objects in a List is not correctly unmarshalled by JSONMarshaller

### PR DESCRIPTION
**Pull request by mswiderski**

### CODE REVIEW

**Comment by mswiderski** [comment]
jenkins retest this

**Comment by mswiderski** [comment]
jenkins retest this

**Comment by mswiderski** [comment]
jenkins retest this

**Comment by tkobayas** [comment]
Thank you @mswiderski , I confirmed that it works for "having type information only on top level object" case as well. FYI, this is the test case I confirmed. You can add it to MarshallingRoundTripCustomClassListTest if you want.
https://gist.github.com/tkobayas/1fac568d9544fe894c919b558f07421f

**Comment by mswiderski** [comment]
Excellent, thanks for confirming. Will include the test as well

**Pull request merged**
