### PR TITLE
[RHBRMS-2546] Kie Server - Creating container has releaseId null

### PR DESCRIPTION
**Pull request by jakubschwan**
Same as on 6.5.x branch (https://github.com/droolsjbpm/droolsjbpm-integration/pull/597)

### CODE REVIEW

**Comment by mswiderski** [comment]
@jakubschwan could you please rebase as there was a fix for compilation error

**Comment by jakubschwan** [comment]
jenkins retest this

**Comment by mswiderski** [comment]
jenkins retest this

**Comment by mswiderski** [comment]
test case failed does not seem to be related but let's retest it once again

**Comment by mswiderski** [comment]
again no space left on device while running the build... @psiroky is it possible to increase the disc or do the cleanup more frequently?

**Comment by psiroky** [comment]
Not easily possible to increase the disc space. I did some config tweaks to run the clean-up more frequently.

**Comment by mswiderski** [comment]
build successful so +1

**Pull request merged**
