### PR TITLE
RHBPMS-4557: NPE when searching nonexistent task using the method Use…

### PR DESCRIPTION
**Pull request by jesuino**
…rTaskServicesClient.findTaskById

### CODE REVIEW

**Comment by psiroky** [comment]
Do we really need full integration test for this? Integration tests are quite time consuming, so we should try to create unit tests for simple fixes like this. WDYT?

**Comment by sutaakar** [comment]
I think it is suitable for this case. There is also checked that endpoint will correctly process not existing task and return proper response and client will handle the response accordingly.

**Comment by mswiderski** [comment]
agreed that it does make sense to have this as integration test. Actually I think that cause we have this as integration test we got these failures captured that are not handled same for JMS, @jesuino would you mind taking a look?

**Comment by mswiderski** [comment]
jenkins retest this

**Comment by MarianMacik** [comment]
After a little bit of research I have found that in JMS there is no exception thrown on the server side so the response is marked as [SUCCESS](https://github.com/droolsjbpm/droolsjbpm-integration/blob/master/kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/JBPMKieContainerCommandServiceImpl.java#L145) since null is returned. On the client side, since it is a SUCCESS, it is simply returned. To have the same behaviour I would suggest to throw an exception like with [UserTaskServiceBase](https://github.com/droolsjbpm/droolsjbpm-integration/blob/master/kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/UserTaskServiceBase.java#L450) so it is handled as a failure for both REST and JMS.

So what do you think?

Marian

**Comment by MarianMacik** [comment]
After a discussion with @psiroky we agreed that I will create a new PR for this with the same handling as in the case of client's getTaskInstance method (handled via exceptions).

**Comment by jesuino** [comment]
I noticed that it would require changes on JMS side and how it deals with exceptions so I was supposed to talk to you about it, but I see @MarianMacik took over this issue, thanks, Marin!

**Comment by mswiderski** [comment]
replaced (and already merged) by https://github.com/droolsjbpm/droolsjbpm-integration/pull/797

**Pull request closed without merging**
