### PR TITLE
DROOLS-1053: Change date formats for JSON representations used in the…

### PR DESCRIPTION
**Pull request by jesuino**
DROOLS-1053: Change date formats for JSON representations used in the REST API

### CODE REVIEW

**Comment by mswiderski** [comment]
+1 will merge it later today, thanks

**Comment by mswiderski** [comment]
btw, do you mind dropping another PR for 6.4.x if it shall go in there?

**Comment by mswiderski** [comment]
cherry-picked to 6.4.x as it was clean merge

**Comment by jesuino** [comment]
Thanks, Maciej!

**Pull request closed without merging**
