### PR TITLE
Updated PerfRepo client to 1.6

### PR DESCRIPTION
**Pull request by ibek**

### CODE REVIEW

**Comment by ibek** [comment]
Please don't merge it yet - I need to do some updates due to the change of the version.

**Comment by ibek** [comment]
Please don't merge it yet - I need to do some updates due to the change of the version.

**Comment by ibek** [comment]
Please don't merge it yet - I need to do some updates due to the change of the version.

**Comment by ibek** [comment]
Please don't merge it yet - I need to do some updates due to the change of the version.

**Comment by mswiderski** [comment]
@ibek is this ready or?

**Comment by ibek** [comment]
@mswiderski yes, we can merge it. I checked that it's working.

**Comment by mswiderski** [comment]
merging as this is only performance tests related

@ibek will we need this on master?

**Comment by ibek** [comment]
Not needed on master yet - the codebase is different there and needs some refactoring - I would include the changes in some future PR

**Pull request merged**
