### PR TITLE
Multiple fixes from the 6.4.x branch

### PR DESCRIPTION
**Pull request by mrietveld**
This PR is meant for the master branch.

See: 

https://github.com/droolsjbpm/droolsjbpm-integration/pull/360
https://github.com/droolsjbpm/droolsjbpm-integration/pull/358
https://github.com/droolsjbpm/droolsjbpm-integration/pull/356

### CODE REVIEW

**Comment by mswiderski** [comment]
compilation error in jbpm that was just fixed with https://github.com/droolsjbpm/jbpm/commit/ba7e30aa2afce0489c4ab35970e4c4a18b64fa15

**Comment by mswiderski** [comment]
jenkins retest this

**Comment by mswiderski** [comment]
+1 will just wait for jenkins to finish the build

**Comment by mrietveld** [comment]
"Caused by: org.apache.maven.wagon.TransferFailedException: Failed to transfer file: https://repository.jboss.org/nexus/content/groups/public/org/dashbuilder/dashbuilder-json/0.5.0-SNAPSHOT/dashbuilder-json-0.5.0-20160317.173050-67.jar. Return code is: 502 , ReasonPhrase:Proxy Error."

**Comment by mrietveld** [comment]
jenkins retest this

**Comment by mrietveld** [comment]
The failing test can be fixed by: https://github.com/droolsjbpm/drools/pull/697

**Pull request closed without merging**
