### PR TITLE
[JBPM-5288] kie-server: scanner status not retained after restart in …

### PR DESCRIPTION
**Pull request by jakubschwan**
…container list

PR for 6.5.x branch: https://github.com/droolsjbpm/droolsjbpm-integration/pull/661
PR for 6.4.x branch: https://github.com/droolsjbpm/droolsjbpm-integration/pull/658

### CODE REVIEW

**Comment by mswiderski** [comment]
jenkins retest this

**Comment by mswiderski** [comment]
and what about this one?

**Comment by psiroky** [comment]
I believe we can close this one in favor of https://github.com/droolsjbpm/droolsjbpm-integration/pull/668

**Comment by psiroky** [comment]
I am closing this in favor #668

**Pull request closed without merging**
