### PR TITLE
kie-server-tests: Case Id generator test

### PR DESCRIPTION
**Pull request by sutaakar**

### CODE REVIEW

**Comment by mswiderski** [comment]
@sutaakar do we need to copy all the car insurance case stuff into the new module? Maybe we could just use simplest possible case definition instead as we don't really need anything advanced there to verify case id generators. Wdyt?

**Comment by sutaakar** [comment]
Right, it could be better, will change it.

**Comment by sutaakar** [comment]
Updated

**Comment by mswiderski** [comment]
thanks @sutaakar

**Pull request merged**
