### PR TITLE
kie-server tests: separated BTM for Tomcat builds

### PR DESCRIPTION
**Pull request by sutaakar**
Removed BTM config files from integration tests which doesn't use BPM extension.
Java 6 fix for OptaPlanner integration test.

### CODE REVIEW

**Comment by mswiderski** [comment]
do we need this for 6.4.x too?

**Comment by sutaakar** [comment]
Yes, it should be cherrypicked into 6.4.x too.

Btw locally I got an exception when running OptaPlanner test:
	org/kie/server/testing/Rule_requiredCpuPowerTotal2067845905.java (2:169) : Only a type can be imported. org.optaplanner.core.api.score.buildin.hardsoft.HardSoftScoreHolder resolves to a package
...

It seems to be unrelated to changes made in this commit, got this error on Tomcat runs and also WildFly.

**Comment by sutaakar** [comment]
That error seems to happen just on 6.4.x branch.

**Comment by mswiderski** [comment]
jenkins retest this

**Pull request closed without merging**
