### PR TITLE
Added optaplanner-core to kie-maven-plugin dependencies to avoid clas…

### PR DESCRIPTION
**Pull request by mswiderski**
…s cast exception on assembler when building projects

@mariofusco @psiroky could you please take a look

### CODE REVIEW

**Comment by mariofusco** [comment]
+1

**Comment by psiroky** [comment]
Would be possible to add a test for this?

**Comment by mswiderski** [comment]
no idea to be honest... can it be done?? since I don't know planner or maven plugin good enough I don't know if we can do it. And we have test in kie server integration tests :)

**Comment by psiroky** [comment]
OK. Let me merge this and I will take a look at creating the test later (since we need to fix those kie-server tests ASAP).

**Pull request merged**
