### PR TITLE
BZ1193122: Various fixes to allow running execution server on Weblogic

### PR DESCRIPTION
**Pull request by sutaakar**
Small changes which allows deployment of execution server on Weblogic.

- raised version of web.xml (caused problem to weblogic) so content become valid
- added weblogic.xml to map security role from web.xml to role group defined in Weblogic
- added destinationJndiName property for JMS - Weblogic use this one for finding out queue JNDI name
- added @ApplicationPath with default value, is overwritten in web.xml - was needed by Weblogic
- removed @Path annotation from REST interface, this annotation in interface caused problems to Weblogic, is duplicated in implementation class anyway

### CODE REVIEW

**Comment by psiroky** [comment]
Thanks! I will look at this asap.

**Comment by psiroky** [comment]
+1. The tests on Tomcat, EAP 6.4 and WildFly 8.x succeeded, everything works as expected.

@etirelli can you please take a quick look, just to verify all the changes are OK?

**Comment by etirelli** [comment]
@psiroky Looks good, can you please merge?

@sutaakar Thanks!

**Comment by psiroky** [comment]
Cherry-picked also into master: https://github.com/droolsjbpm/droolsjbpm-integration/commit/0d9e608d000ea782aa5eb1dfd0b2f9dd94f7fa99

**Pull request merged**
