### PR TITLE
[DROOLS-1267] allow to submit atomic actions during a fireUntilHalt

### PR DESCRIPTION
**Pull request by tarilabs**
alignments for droolsjbpm-integration of Kie API change

### CODE REVIEW

**Comment by tarilabs** [comment]
Jenkins, test this please?

**Comment by psiroky** [comment]
Jenkins is unfortunately out of order currently :(

**Comment by tarilabs** [comment]
@mariofusco I believe DROOLS-1267 requires this on droolsjbpm-integration too.

(assuming will pass the build when Jenkins comes back)

**Comment by tarilabs** [comment]
[`06:29:23 Caused by: java.io.IOException: Server returned HTTP response code: 503 for URL: https://kie-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/maven-repo-cache/lastSuccessfulBuild/artifact/maven-repo-cache.tar.gz`]

Jenkins, test again :8ball:

**Comment by tarilabs** [comment]
org.drools.karaf.itest.blueprint.KieBlueprintImportIntegrationTest.kieElementsExistTest
org.drools.karaf.itest.blueprint.KieBlueprintImportIntegrationTest.kieSessionOldPersonTest
org.drools.karaf.itest.blueprint.KieBlueprintImportIntegrationTest.kieSessionYoungPersonTest
with `gave up waiting for service org.kie.api.runtime.KieSession`

Jenkins, test again :8ball: :8ball:

**Comment by mswiderski** [comment]
these test failures are not related so I opt at merging this as it clocks other prs due to compilation errors. 

P.S.
same goes for 6.5.x branch....

**Comment by psiroky** [comment]
I agree, +1 to merge

**Comment by mswiderski** [comment]
@tarilabs do you mind preparing PR for 6.5.x with these changes? I'll merge this one

**Pull request merged**
