### PR TITLE
[DROOLS-465,BZ-1304051] install test kjars instead of deploying

### PR DESCRIPTION
**Pull request by psiroky**

### CODE REVIEW

**Comment by psiroky** [comment]
@mariofusco please take a look, thanks!

**Comment by mswiderski** [comment]
I guess this is needed as part of this PR too https://github.com/droolsjbpm/droolsjbpm-integration/commit/2dfce3abdc192b05cb14252cd588d44905affa39

**Comment by psiroky** [comment]
@mswiderski yes, correct. I will cherry-pick it here as well.

**Comment by mswiderski** [comment]
+1

**Comment by psiroky** [comment]
Merged into 6.3.x.

**Pull request closed without merging**
